### ISSUE TITLE
能否同时挂载多个相机进行多视图方面的研究学习

### ISSUE THREAD

**Issue by GANWANSHUI** [xiaofeng94/renderdoc_for_game_data#5]
您好， 感谢作者的开源分享，

想请教您，GTA V 里边能同时挂载多个相机，然后渲染各个相机G-BUFFER里的内容吗？主要是面向驾驶场景，想采集一些数据来使用。网上找了一下，但是还没有发现可行的办法。再次感谢！

**Comment by xiaofeng94** [comment]
Hey,

可以查询Script Hook V和相关Mod，见https://zh.gta5-mods.com/tools
其中也许有可以编辑相机的功能

**Comment by GANWANSHUI** [comment]
好的，感谢，我去看看！
